#include <bits/stdc++.h>
using namespace std;using U=uint64_t;struct Key{U lo,hi;bool operator==(Key const&o)const{return lo==o.lo&&hi==o.hi;}bool operator<(Key const&o)const{return hi<o.hi||(hi==o.hi&&lo<o.lo);}};struct Hash{size_t operator()(Key const&k)const{return k.lo^(k.hi*0x9e3779b97f4a7c15ULL);}};
vector<int>E8,E7,T;int ix8[256],ix7[128];unordered_set<U>allowed;unordered_set<Key,Hash>answer;
Key canonical(vector<int>const&A){int deg[8]={};for(int a:A)for(int i=0;i<8;i++)deg[i]+=a>>i&1;vector<pair<int,int>>v;for(int i=0;i<8;i++)v.push_back({deg[i],i});sort(v.begin(),v.end());vector<vector<int>>gr;vector<int>st;for(int i=0;i<8;){int j=i;vector<int>g;while(j<8&&v[j].first==v[i].first)g.push_back(v[j++].second);sort(g.begin(),g.end());gr.push_back(g);st.push_back(i);i=j;}int p[8];Key best{~U(0),~U(0)};function<void(int)>go=[&](int k){if(k<(int)gr.size()){auto g=gr[k];do{for(int j=0;j<(int)g.size();j++)p[g[j]]=st[k]+j;go(k+1);}while(next_permutation(g.begin(),g.end()));return;}Key f{0,0};for(int a:A){int b=0;for(int i=0;i<8;i++)if(a>>i&1)b|=1<<p[i];int idx=ix8[b];if(idx<64)f.lo|=U(1)<<idx;else f.hi|=U(1)<<(idx-64);}if(f<best)best=f;};go(0);return best;}
int compress(int a,int i){return (a&((1<<i)-1))|((a>>(i+1))<<i);}
int main(int argc,char**argv){int target=argc>1?atoi(argv[1]):11;for(int a=0;a<256;a++)if(__builtin_popcount((unsigned)a)==4){ix8[a]=E8.size();E8.push_back(a);if(a<128){ix7[a]=E7.size();E7.push_back(a);}}for(int a=0;a<128;a++)if(__builtin_popcount((unsigned)a)==3)T.push_back(a);
 {ifstream in("data/nonfc7_labeled.bin",ios::binary);U a;while(in.read((char*)&a,8))allowed.insert(a);}
 U extra[7][35];for(int i=0;i<7;i++)for(int j=0;j<35;j++)extra[i][j]=(T[j]>>i&1)?0:U(1)<<ix7[compress(T[j]|128,i)];
 long long visits=0,leaves=0,local_pruned=0,degree_pruned=0;int cases=0;auto start=chrono::steady_clock::now();int m;
 while(cin>>m){vector<int>A(m);for(int&a:A)cin>>a;int d=target-m;if(d<0||d>target/2||d>35)continue;cases++;array<U,7>r{};array<int,7>deg{};for(int a:A)for(int i=0;i<7;i++){deg[i]+=a>>i&1;if(!(a>>i&1))r[i]|=U(1)<<ix7[compress(a,i)];}
 function<void(int,int,array<U,7>const&,array<int,7>const&)>go=[&](int pos,int left,array<U,7>const&rr,array<int,7>const&dd){visits++;if(!left){leaves++;for(int i=0;i<7;i++)if(dd[i]<d){degree_pruned++;return;}answer.insert(canonical(A));return;}for(int i=0;i<7;i++)if(dd[i]+left<d){degree_pruned++;return;}for(int j=pos;j<=35-left;j++){auto r2=rr;auto d2=dd;bool ok=true;for(int i=0;i<7;i++){r2[i]|=extra[i][j];d2[i]+=T[j]>>i&1;if(!allowed.count(r2[i])){ok=false;break;}}if(!ok){local_pruned++;continue;}A.push_back(128|T[j]);go(j+1,left-1,r2,d2);A.pop_back();}};
 go(0,d,r,deg);if(cases%20==0)cerr<<"cases "<<cases<<" visits "<<visits<<" leaves "<<leaves<<" orbits "<<answer.size()<<" seconds "<<chrono::duration<double>(chrono::steady_clock::now()-start).count()<<"\n";
 }
 vector<Key>out(answer.begin(),answer.end());sort(out.begin(),out.end());for(auto f:out){cout<<f.lo<<" "<<f.hi;for(int i=0;i<70;i++)if(i<64?(f.lo>>i&1):(f.hi>>(i-64)&1))cout<<" "<<E8[i];cout<<"\n";}cerr<<"DONE target "<<target<<" cases "<<cases<<" visits "<<visits<<" leaves "<<leaves<<" local_pruned "<<local_pruned<<" degree_pruned "<<degree_pruned<<" orbits "<<out.size()<<" seconds "<<chrono::duration<double>(chrono::steady_clock::now()-start).count()<<"\n";
}
